{% set name = "osmnx" %}
{% set version = "1.9.4" %}
{% set sha256 = "5083baa1fc2964f9210396feccfb25429430f083ef41e22b70f3e645ae6247dd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch
    - pip
    - python >=3.8
  run:
    - folium
    - gdal
    - geopandas >=0.12,<0.15
    - matplotlib-base >=3.5,<3.9
    - networkx >=2.5,<3.4
    - numpy >=1.20,<1.27
    - pandas >=1.1,<2.3
    - python >=3.8
    - rasterio >=1.3,<1.4
    - requests >=2.27,<2.33
    - scipy >=1.5,<1.14
    - scikit-learn >=0.23,<1.6
    - shapely >=2.0,<2.1

test:
  imports:
    - osmnx

about:
  home: https://osmnx.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap.
  description: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap. You can download and model walking, driving, or biking networks with a single line of code then analyze and visualize them. You can just as easily work with urban amenities/points of interest, building footprints, transit stops, elevation data, street orientations, speed/travel time, and routing.
  doc_url: https://osmnx.readthedocs.io
  dev_url: https://github.com/gboeing/osmnx

extra:
  recipe-maintainers:
    - gboeing
    - ocefpaf
