{% set name = "osmnx" %}
{% set version = "2.0.0" %}
{% set sha256 = "4fd2eb3736cea503be94ab18d31a669addbaf2dd6a8249527cef94163bb93975" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch
    - pip
    - python >=3.9
  run:
    - geopandas >=1.0
    - matplotlib-base >=3.5
    - networkx >=2.5
    - numpy >=1.22
    - pandas >=1.4
    - python >=3.9
    - rasterio >=1.3
    - requests >=2.27
    - rio-vrt >=0.3
    - scikit-learn >=0.23
    - scipy >=1.5
    - shapely >=2.0

test:
  imports:
    - osmnx

about:
  home: https://osmnx.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap.
  description: OSMnx is a Python package to easily download, model, analyze, and visualize street networks and other geospatial features from OpenStreetMap. You can download and model walking, driving, or biking networks with a single line of code then analyze and visualize them. You can just as easily work with urban amenities/points of interest, building footprints, transit stops, elevation data, street orientations, speed/travel time, and routing.
  doc_url: https://osmnx.readthedocs.io
  dev_url: https://github.com/gboeing/osmnx

extra:
  recipe-maintainers:
    - gboeing
    - ocefpaf
